apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: andrusdiaz
resources:
  - serviceaccount.yaml
  - nginx-config.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: aura-mesh
    newName: southamerica-east1-docker.pkg.dev/gen-lang-client-0331944990/aura-mesh/aura-mesh
    digest: sha256:101cbbc178546d2a50b5c0fe64ba5347aee96009eeb9aab41b05a727eab8f3e5

