apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: andrusdiaz
resources:
  - serviceaccount.yaml
  - nginx-config.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: aura-mesh
    newName: southamerica-east1-docker.pkg.dev/gen-lang-client-0331944990/aura-mesh/aura-mesh
    digest: sha256:6bf5f58eac5d4d99be51d0e3c22496858a3139ae459a6ba37a8f288778d4d098

