apiVersion: v1
kind: ServiceAccount
metadata:
  name: aura-mesh
  labels:
    app.kubernetes.io/name: aura-mesh
    app.kubernetes.io/part-of: andrusdiaz
automountServiceAccountToken: false
imagePullSecrets:
  - name: artifact-registry

